### ISSUE TITLE
[AVM Module Issue]: Disk creation issue - first data disk not working correctly?

### ISSUE THREAD

**Issue by AntRobinson** [Azure/terraform-azurerm-avm-res-compute-virtualmachine#192]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

avm-res-compute-virtualmachine - 0.18.0

### Description

I am coming across an issue when creating a VM with data disks attached to it. As part of our deployment we onboard our VMs to our DSC in azure (which initializes data disks) however the DSC refuses to "acknowledge" the first data disk. When we deploy the exact same VMs through ARM we do not encounter an issue. In addition, the terraform state file does not get updated with disk encryption settings, after Azure disk encryption extension is installed.

Please find my yaml and .tf file

YAML:
```
# Validation on what is or isnt optional, null or empty checks

app-code: "0850"                                          # Required
identifier: "id2"                                         # Required
location: "uksouth"                                       # Required / uksouth or ukwest
env-number: "1"                                           # Required / 2 or higher!
rsv-cross-region-restore-enabled: true
rsv-subnet: subnet-nsg2                                   # Required

app-vms:
  vm1app:                                                 # At least one VM is required
    windows-version: 2016                                      # Required / Only 2016 or 2022 image
    sku: "Standard_D4s_v3"                                # Required
    zone: "1"                                             # Required / Numbers between zones 1 and 3
    type: "app"                                           # Required
    subnet: "subnet-nsg1"                                 # Required / Validate this value exists in subnet section.
    private-ip-address: "xx.xx.xx.37"                    # Required / Is valid ip format, Check is within allocated subnet cidr range.
    domain:                                  # Check domain script for parameters
      custom-permissions: ""                                 # Check domain script for any validation
    dsc-node-configuration-name: "DataHub_App"  # Check dsc nodes script
    os-disk:
      storage-account-type: "Premium_LRS"                 # Required
      size: 128                                           # Required / 128 minimum
    data-disks:
      disk1:
        caching: "ReadWrite"
        size: 64
        storage-account-type: "Premium_LRS"
        letter: "F"
    tags:
      test-vm1: "test-app-vm-value1"
      test-vm2: "test-app-vm-value2"
  vm2app:                                                 # At least one VM is required
    windows-version: 2016                                      # Required / Only 2016 or 2022 image
    sku: "Standard_D4s_v3"                                # Required
    zone: "1"                                             # Required / Numbers between zones 1 and 3
    type: "app"                                           # Required
    subnet: "subnet-nsg1"                                 # Required / Validate this value exists in subnet section.
    private-ip-address: "xx.xx.xx.38"                    # Required / Is valid ip format, Check is within allocated subnet cidr range.
    domain:                                   # Check domain script for parameters
      custom-permissions: ""                                  # Check domain script for any validation
    dsc-node-configuration-name: "DataHub_App"   # Check dsc nodes script
    os-disk:
      storage-account-type: "Premium_LRS"                 # Required
      size: 128                                           # Required / 128 minimum
    data-disks:
      disk1:
        caching: "ReadWrite"
        size: 64
        storage-account-type: "Premium_LRS"
        letter: "F"
    tags:
      test-vm1: "test-app-vm-value1"
      test-vm2: "test-app-vm-value2"
sql-vms:
  vm1sql:
    windows-version: 2016
    sql-version: 2022
    sku: "Standard_D4s_v3"
    zone: "1"
    type: "sql"
    subnet: "subnet-nsg1"
    private-ip-address: "xx.xx.xx.39"
    domain:
      custom-permissions: ""
    dsc-node-configuration-name: "DataHub_SQL"
    os-disk:
      storage-account-type: "Premium_LRS"
      size: 128
    data-disks:
      disk1:
        caching: "ReadWrite"
        size: 64
        storage-account-type: "Premium_LRS"
        letter: "E"
      disk2:
        caching: "ReadWrite"
        size: 64
        storage-account-type: "Premium_LRS"
        letter: "H"
      disk3:
        caching: "ReadWrite"
        size: 64
        storage-account-type: "Premium_LRS"
        letter: "I"
      disk4:
        caching: "ReadWrite"
        size: 64
        storage-account-type: "Premium_LRS"
        letter: "W"
      disk5:
        caching: "ReadWrite"
        size: 64
        storage-account-type: "Premium_LRS"
        letter: "T" 
    tags: 
      test-vm1: "test-sql-vm-value1"
      test-vm2: "test-sql-vm-value2"
  vm2sql:
    windows-version: 2022
    sql-version: 2022
    sku: "Standard_F8s_v2"
    zone: "2"
    type: "sql"
    subnet: "subnet-nsg1"
    private-ip-address: "xx.xx.xx.40"
    domain:
      custom-permissions: ""
    dsc-node-configuration-name: "Win22_Generic_SQL_id2_disk_issue"
    os-disk:
      storage-account-type: "Premium_LRS"
      size: 128
    data-disks:
      disk1:
        caching: "ReadWrite"
        size: 64
        storage-account-type: "Premium_LRS"
        letter: "E"
      disk2:
        caching: "ReadWrite"
        size: 64
        storage-account-type: "Premium_LRS"
        letter: "H"
      disk3:
        caching: "ReadWrite"
        size: 64
        storage-account-type: "Premium_LRS"
        letter: "I"
      disk4:
        caching: "ReadWrite"
        size: 64
        storage-account-type: "Premium_LRS"
        letter: "W"
      disk5:
        caching: "ReadWrite"
        size: 64
        storage-account-type: "Premium_LRS"
        letter: "T"
    tags: 
      test-vm1: "test-sql-vm-value1"
      test-vm2: "test-sql-vm-value2"

```
.tf file

```
module "virtual-machine" {
  source           = "Azure/avm-res-compute-virtualmachine/azurerm"
  version          = "0.18.0"
  enable_telemetry = false

  for_each = local.virtual-machines-to-deploy

  resource_group_name = local.rg-name-prefix
  name                = local.virtual-machine-names[each.key]
  location            = local.infra-deployment-data-map.location

  admin_username = local.virtual-machine-local-admin-username
  admin_password = random_password.vm-local-admin-password.result

  bypass_platform_safety_checks_on_user_schedule_enabled = true

  azure_backup_configurations = {
    default-virtual-machine-policy = {
      recovery_vault_resource_id = module.recovery-service-vault.resource_id
      backup_policy_resource_id = (
        resource.azurerm_backup_policy_vm.main[each.value.windows-version == 2022 ? 1 : 0].id
      )
    }
  }

  boot_diagnostics = true

  data_disk_managed_disks = {

    for disk-key, disk-value in each.value.data-disks : disk-key => ({

      caching       = disk-value.caching
      create_option = "Empty"
      disk_size_gb  = disk-value.size

      lun = index(keys(each.value.data-disks), disk-key)
      name = (
        "${local.virtual-machine-names[each.key]}_${disk-value.letter}_${local.virtual-machine-name-disk-prefix}01"
      )
      storage_account_type = disk-value.storage-account-type
    })
  }

  enable_automatic_updates   = false
  encryption_at_host_enabled = false

  extensions = {
    azure-disk-encryption = {
      name                       = "AzureDiskEncryption"
      deploy_sequence            = 3
      publisher                  = "Microsoft.Azure.Security"
      type                       = "AzureDiskEncryption"
      type_handler_version       = "2.2"
      auto_upgrade_minor_version = true
      settings                   = <<SETTINGS
        {
          "EncryptionOperation": "EnableEncryption",
          "KeyVaultURL": "${data.azurerm_key_vault.infra-keyvault.vault_uri}",
          "KeyVaultResourceId": "${module.keyvault.infra-keyvault.resource_id}",
          "KeyEncryptionAlgorithm": "RSA-OAEP",
          "VolumeType": "All"
        }
        SETTINGS
    }

    azure-network-watcher-extension = {
      name                       = "AzureNetworkWatcherExtension"
      deploy_sequence            = 2
      publisher                  = "Microsoft.Azure.NetworkWatcher"
      type                       = "NetworkWatcherAgentWindows"
      type_handler_version       = "1.4"
      auto_upgrade_minor_version = true
    }
    
    bg-info-extension = {
      name = "BGInfo"
      deploy_sequence = 2
      publisher = "Microsoft.Compute"
      type = "bginfo"
      type_handler_version = "2.1"
      auto_upgrade_minor_version = true
    }

    iaas-anti-malware-extension = {
      name = "IaaSAntimalware"
      deploy_sequence = 2
      publisher = "Microsoft.Azure.Security"
      type = "IaaSAntimalware"
      type_handler_version = "1.3"
      auto_upgrade_minor_version = true
            settings                   = <<SETTINGS
        {
          "AntimalwareEnabled": "true",
          "RealtimeProtectionEnabled": "true",
          "ScheduledScanSettings": {
            "isEnabled": "false",
            "day": "7",
            "time": "590",
            "scanType": "Quick"
          }
        }
        SETTINGS
    }
    # NOTE: You cant have multiple Custom Script Extensions on a single VM.
    # Our old deployment method gets around this by separating the deployment of these extensions into separate pipeline stages.
    # With the extension in the next pipeline stage overwriting the former as the next extension resource has the same name. 
    # This approach will not work with TF and how it manages state, to get around this, all scripts are merged into a single extension.
    # Domain join script is now last because it restarts the VM.
    custom-script-extensions = {
      name                 = "CustomScriptExtension"
      deploy_sequence      = 1
      publisher            = "Microsoft.Compute"
      type                 = "CustomScriptExtension"
      type_handler_version = "1.10"
      #TODO: Test windows firewall
      protected_settings = <<PROTECTED_SETTINGS
        {
          "commandToExecute" : "powershell -ExecutionPolicy Unrestricted -Command \"${local.vm-ps-commands[each.key].onboard-dsc}; ${local.vm-ps-commands[each.key].windows-firewall}; ${local.vm-ps-commands[each.key].qualys-snare}; ${local.vm-ps-commands[each.key].domain-join}${local.vm-ps-commands[each.key].domain-group-suffix}${local.vm-ps-commands[each.key].domain-permission-suffix}\"",
          "FileUris": [
              "${local.domain-script-uri[var.DEPLOYMENTTENANT]}${data.azurerm_storage_account_sas.component-sas.sas}",
              "${local.dsc-script-uri[var.DEPLOYMENTTENANT]}${data.azurerm_storage_account_sas.component-sas.sas}",
              "${local.qualys-snare-script-uri[var.DEPLOYMENTTENANT]}${data.azurerm_storage_account_sas.component-sas.sas}",
              "${local.windows-firewall-script-uri[var.DEPLOYMENTTENANT]}${data.azurerm_storage_account_sas.component-sas.sas}"
          ]
        }
        PROTECTED_SETTINGS       
    }
  }

  generate_admin_password_or_ssh_key = false

  generated_secrets_key_vault_secret_config = {
    key_vault_resource_id = module.keyvault.infra-keyvault.resource_id
  }

  license_type = "Windows_Server"

  managed_identities = {
    system_assigned = true
    user_assigned_resource_ids = [
      azurerm_user_assigned_identity.vm-identity.id,
      data.azurerm_user_assigned_identity.aut-storage-account-reader.id
    ]
  }

  network_interfaces = {
    main-nic = {
      name = local.virtual-machine-nic-names[each.key]

      ip_configurations = {
        private = {
          name                          = "private"
          private_ip_subnet_resource_id = module.subnet[each.value.subnet].resource_id
          private_ip_address            = each.value.private-ip-address
          private_ip_address_allocation = "Static"
        }
      }
    }
  }

  os_disk = {
    caching              = "ReadWrite"
    storage_account_type = each.value.os-disk.storage-account-type
    disk_size_gb         = each.value.os-disk.size
    name                 = "${local.virtual-machine-names[each.key]}_C_${local.virtual-machine-name-disk-prefix}01"
  }

  os_type               = "windows"
  patch_assessment_mode = "AutomaticByPlatform"
  patch_mode            = "AutomaticByPlatform"
  secure_boot_enabled   = each.value.windows-version == 2022

  sku_size                 = each.value.sku
  source_image_resource_id = local.virtual-machine-image-ids["${var.DEPLOYMENTTENANT}-${each.value.windows-version}"]
  tags                     = merge(local.infra-deployment-data-map.tags, (!contains(keys(each.value.tags), "tags")) ? tomap({}) : (each.value.tags != null) ? each.value.tags : tomap({}))
  zone                     = each.value.zone
}

resource "azurerm_user_assigned_identity" "vm-identity" {
  location            = local.infra-deployment-data-map.location
  name                = "${local.identity-name-prefix}01"
  resource_group_name = local.rg-name-prefix
}

resource "azurerm_role_assignment" "virtual-machine-resource-group-reader" {
  scope                = data.azurerm_resource_group.virtual-machine-resource-group.id
  role_definition_name = "Reader"
  principal_id         = azurerm_user_assigned_identity.vm-identity.principal_id
}

resource "azurerm_role_assignment" "virtual-network-resource-group-reader" {
  scope                = data.azurerm_resource_group.virtual-network-resource-group.id
  role_definition_name = "Reader"
  principal_id         = azurerm_user_assigned_identity.vm-identity.principal_id
}

resource "random_password" "vm-local-admin-password" {
  length           = 22
  min_lower        = 2
  min_numeric      = 2
  min_special      = 2
  min_upper        = 2
  override_special = "!#$%&*()-_=+[]{}<>:?"
  special          = true
}
```
